POST http://localhost:5000/users/register
Content-Type: application/json

{
    "fullName": "Isaac Kilimo",
    "email": "kilimok2@gmail.com",
    "password": "12345678"
}


### login 
POST http://localhost:5000/users/login
Content-Type: application/json

{
   "email": "kilimok2@gmail.com",
   "password": "12345678" 
}

### fetching users
GET http://localhost:5000/users/
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjgwZjg2MmMtMTgwYy00NThlLTlkMDAtNGIyNTEwNGVlNzFhIiwiZnVsbE5hbWUiOiJtaWxseSBtaWxsaWNlbnQyIiwiZW1haWwiOiJtaWxsaWUyQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDA1JFF2TW1ScWlHQlpDZWY4a1FGTjZ4ck9KRnhYNTZ4MS43NW9jeHI1cVBkeTEyMmx4MDVDSjVlIiwicm9sZSI6InVzZXIiLCJ3ZWxjb21lZCI6ZmFsc2UsImlhdCI6MTY5ODg2Mzg3OSwiZXhwIjoxNjk5MDM2Njc5fQ.mgaY5zy5d-kbmtp7FLfXstynIO4612f7bB57k_1l5rg


### checking user details
GET http://localhost:5000/users/checkUserDetails
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjgwZjg2MmMtMTgwYy00NThlLTlkMDAtNGIyNTEwNGVlNzFhIiwiZnVsbE5hbWUiOiJtaWxseSBtaWxsaWNlbnQyIiwiZW1haWwiOiJtaWxsaWUyQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDA1JFF2TW1ScWlHQlpDZWY4a1FGTjZ4ck9KRnhYNTZ4MS43NW9jeHI1cVBkeTEyMmx4MDVDSjVlIiwicm9sZSI6InVzZXIiLCJ3ZWxjb21lZCI6ZmFsc2UsImlhdCI6MTY5ODg2Mzg3OSwiZXhwIjoxNjk5MDM2Njc5fQ.mgaY5zy5d-kbmtp7FLfXstynIO4612f7bB57k_1l5rg


######
POST http://localhost:5000/project/
Content-Type: application/json

{
    "project_name": "Angular Updates",
    "description": "to be ready by this weekend",
    "endDate": "12/13/2020"
}

### fetching users
GET http://localhost:5000/project/



# Deleting a note
###
DELETE http://localhost:5000/project/b5c6906b-3e90-44b8-b2dc-73dee6f3085a/


###
POST http://localhost:5000/project/assign
Content-Type: application/json

{
    "user_id": "",
    "project_id": "e56e3b97-bbc3-4fb0-a678-14082a741a49",
}